project:
  type: website

website:
  title: "Do Phone Bans at School Really do Anything?"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model.qmd
        text: Model
      - href: source.qmd
        text: Source
      - href: about.qmd
        text: About

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    toc-location: left
    author: "Anthony Gao"




